<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="4" ignored="0" total="4" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="6916" started-at="2020-07-30T21:35:39 IST" finished-at="2020-07-30T21:35:46 IST">
    <groups>
    </groups>
    <test name="Default test" duration-ms="6916" started-at="2020-07-30T21:35:39 IST" finished-at="2020-07-30T21:35:46 IST">
      <class name="com.qa.Gorest.testcases.PutCallAPI">
        <test-method status="FAIL" signature="callPUT_DataProvider(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.qa.Gorest.testcases.PutCallAPI@3712b94]" name="callPUT_DataProvider" duration-ms="3709" started-at="2020-07-30T21:35:39 IST" data-provider="readit" finished-at="2020-07-30T21:35:43 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[DOO]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Babu]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[male]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[12-Dec-1986]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[dil@yahoo.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[9876543210]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[https://www.naveenautomation.com]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[Texus,United States]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[active]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [302] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [302] but found [404]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.qa.Gorest.testcases.PutCallAPI.callPUT_DataProvider(PutCallAPI.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- callPUT_DataProvider -->
        <test-method status="FAIL" signature="callPUT_DataProvider(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.qa.Gorest.testcases.PutCallAPI@3712b94]" name="callPUT_DataProvider" duration-ms="1097" started-at="2020-07-30T21:35:43 IST" data-provider="readit" finished-at="2020-07-30T21:35:44 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[raj]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Babu]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[male]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[12-Dec-1986]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[dil@yahoo.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[9876543210]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[https://www.naveenautomation.com]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[Texus,United States]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[active]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [302] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [302] but found [404]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.qa.Gorest.testcases.PutCallAPI.callPUT_DataProvider(PutCallAPI.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- callPUT_DataProvider -->
        <test-method status="FAIL" signature="callPUT_DataProvider(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.qa.Gorest.testcases.PutCallAPI@3712b94]" name="callPUT_DataProvider" duration-ms="846" started-at="2020-07-30T21:35:44 IST" data-provider="readit" finished-at="2020-07-30T21:35:45 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[raj]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Babu]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[male]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[12-Dec-1986]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[dil@yahoo.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[9876543210]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[https://www.naveenautomation.com]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[Texus,United States]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[active]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [302] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [302] but found [404]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.qa.Gorest.testcases.PutCallAPI.callPUT_DataProvider(PutCallAPI.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- callPUT_DataProvider -->
        <test-method status="FAIL" signature="callPUT_DataProvider(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.qa.Gorest.testcases.PutCallAPI@3712b94]" name="callPUT_DataProvider" duration-ms="831" started-at="2020-07-30T21:35:45 IST" data-provider="readit" finished-at="2020-07-30T21:35:46 IST">
          <params>
            <param index="0">
              <value>
                <![CDATA[DOO]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Babu]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[male]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[12-Dec-1986]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[dil@yahoo.com]]>
              </value>
            </param>
            <param index="5">
              <value>
                <![CDATA[9876543210]]>
              </value>
            </param>
            <param index="6">
              <value>
                <![CDATA[https://www.naveenautomation.com]]>
              </value>
            </param>
            <param index="7">
              <value>
                <![CDATA[Texus,United States]]>
              </value>
            </param>
            <param index="8">
              <value>
                <![CDATA[active]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
expected [302] but found [404]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [302] but found [404]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at com.qa.Gorest.testcases.PutCallAPI.callPUT_DataProvider(PutCallAPI.java:54)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- callPUT_DataProvider -->
      </class> <!-- com.qa.Gorest.testcases.PutCallAPI -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
